# Generated by Django 5.0.3 on 2024-08-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
