# Generated by Django 5.0.3 on 2024-08-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0004_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
